@startuml
actor "Researcher" as User
participant "User \n Interface" as ui
participant Simulation
participant "Data \n Storage" as ds
participant "Area \n Coverage \n Algorithm" as area
participant "Insect \n tracking" as tracking
participant "Insect \n Measurement \n Sensors" as sensors
participant "Server \n Communication \n interface" as servercomm
participant "Insect \n User \n Communication \n interface" as insectcomm
participant "Insect \n Motor \n Control" as imc

activate User #FFBBBB
User -> ui : ViewProgress()
activate ui #FFBBBB


ui -> area : getDetails()
activate area #FFBBBB
area -> ds : query(surveyDetails)

activate ds #FFBBBB
ds --> area : return data
deactivate ds

area -> area : calcProgress(data)

area --> ui : return results

deactivate area

ui --> User : DisplayResults()

deactivate ui
deactivate User
@enduml
