@startuml
hide empty description
state "Start Simulation" as start
state "End Simulation" as end
state "Run Simulation" as run
' state "Get insect location" as update
state "Update insect location" as path
state "Update insect path" as hist
[*] -right-> start
start -right-> run 
run -right-> path : Survey Not complete
' update --> path
path --> hist
hist --> run
run --> end : Survey Complete
end --> [*]
@enduml
