@startuml
actor "Researcher" as User
participant "User \n Interface" as ui
participant Simulation
participant "Data \n Storage" as ds
participant "Area \n Coverage \n Algorithm" as area
participant "Insect \n tracking" as tracking
participant "Insect \n Measurement \n Sensors" as sensors
participant "Server \n Communication \n interface" as servercomm
participant "Insect \n User \n Communication \n interface" as insectcomm
participant "Insect \n Motor \n Control" as imc

activate User #FFBBBB
User -> ui : stop()
activate ui #FFBBBB
deactivate User

ui -> area : returnToBase()
deactivate ui
activate area #FFBBBB
area -> ds : insert(details)
activate ds #FFBBBB
deactivate ds
deactivate area



@enduml
